name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test --enable-test-discovery
